import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import ConditionalLayout from '@/components/ConditonalLayout'
import ContextProvider from '@/utils/Context'
import Navbar from '@/components/Navbar'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SASSAI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <div className=" flex flex-col">
            <ConditionalLayout>
              {children} <Toaster />
            </ConditionalLayout>
            <></>
          </div>
        </ContextProvider>
      </body>
    </html>
  )
}
